[project]
name = "jupinote"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "notebook>=7.4.5",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
